CREATE DATABASE dhoni;

USE dhoni;


CREATE TABLE PEOPLE (name VARCHAR(50),
phn INT PRIMARY KEY,
address VARCHAR(50)
);

INSERT INTO  PEOPLE (name,phn,address) VALUES ("VAZID",43,"NELLORE"),("DHONI",7,"CHENNAI");
INSERT INTO PEOPLE VALUES("AYESHA",11,"VAKADU");
SELECT* FROM PEOPLE;


